
package soap.services.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Sat Nov 26 18:43:57 CET 2016
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "getBenutzerliste", namespace = "http://services.soap/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getBenutzerliste", namespace = "http://services.soap/")

public class GetBenutzerliste {


}

