
package soap.services.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Sat Nov 26 18:43:57 CET 2016
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "getBenutzerlisteResponse", namespace = "http://services.soap/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getBenutzerlisteResponse", namespace = "http://services.soap/")

public class GetBenutzerlisteResponse {

    @XmlElement(name = "return")
    private java.util.List<modell.Benutzer> _return;

    public java.util.List<modell.Benutzer> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.List<modell.Benutzer> new_return)  {
        this._return = new_return;
    }

}

