
package soap.services.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Sat Jan 21 21:51:17 CET 2017
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "getProduktgruppeListResponse", namespace = "http://services.soap/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getProduktgruppeListResponse", namespace = "http://services.soap/")

public class GetProduktgruppeListResponse {

    @XmlElement(name = "return")
    private java.util.List<modell.Produktgruppe> _return;

    public java.util.List<modell.Produktgruppe> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.List<modell.Produktgruppe> new_return)  {
        this._return = new_return;
    }

}

