
package soap.services.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Sat Jan 21 19:03:46 CET 2017
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "getProduktListeOhneResponse", namespace = "http://services.soap/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getProduktListeOhneResponse", namespace = "http://services.soap/")

public class GetProduktListeOhneResponse {

    @XmlElement(name = "return")
    private java.util.List<modell.ProduktOhneGruppe> _return;

    public java.util.List<modell.ProduktOhneGruppe> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.List<modell.ProduktOhneGruppe> new_return)  {
        this._return = new_return;
    }

}

