
package soap.services.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Sat Jan 21 15:27:32 CET 2017
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "getProduktByIDResponse", namespace = "http://services.soap/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getProduktByIDResponse", namespace = "http://services.soap/")

public class GetProduktByIDResponse {

    @XmlElement(name = "return")
    private modell.Produkt _return;

    public modell.Produkt getReturn() {
        return this._return;
    }

    public void setReturn(modell.Produkt new_return)  {
        this._return = new_return;
    }

}

