
package soap.services.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Sat Jan 21 15:27:32 CET 2017
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "produktVerschieben", namespace = "http://services.soap/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "produktVerschieben", namespace = "http://services.soap/", propOrder = {"arg0", "arg1"})

public class ProduktVerschieben {

    @XmlElement(name = "arg0")
    private java.util.UUID arg0;
    @XmlElement(name = "arg1")
    private java.lang.String arg1;

    public java.util.UUID getArg0() {
        return this.arg0;
    }

    public void setArg0(java.util.UUID newArg0)  {
        this.arg0 = newArg0;
    }

    public java.lang.String getArg1() {
        return this.arg1;
    }

    public void setArg1(java.lang.String newArg1)  {
        this.arg1 = newArg1;
    }

}

