package client.soap.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2016-11-26T18:48:43.827+01:00
 * Generated source version: 3.1.8
 * 
 */
@WebService(targetNamespace = "http://services.soap/", name = "BenutzerservicesSEI")
@XmlSeeAlso({ObjectFactory.class})
public interface BenutzerservicesSEI {

    @WebMethod
    @RequestWrapper(localName = "pruefeLogin", targetNamespace = "http://services.soap/", className = "soap.services.PruefeLogin")
    @ResponseWrapper(localName = "pruefeLoginResponse", targetNamespace = "http://services.soap/", className = "soap.services.PruefeLoginResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean pruefeLogin(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "getBenutzerliste", targetNamespace = "http://services.soap/", className = "soap.services.GetBenutzerliste")
    @ResponseWrapper(localName = "getBenutzerlisteResponse", targetNamespace = "http://services.soap/", className = "soap.services.GetBenutzerlisteResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<client.soap.services.Benutzer> getBenutzerliste();
}
