package client.soap.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2016-11-26T18:48:43.831+01:00
 * Generated source version: 3.1.8
 * 
 */
@WebServiceClient(name = "BenutzerservicesService", 
                  wsdlLocation = "http://localhost:8080/DSE_Abgabe2Projekt/services/BenutzerservicesPort?wsdl",
                  targetNamespace = "http://services.soap/") 
public class BenutzerservicesService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://services.soap/", "BenutzerservicesService");
    public final static QName BenutzerservicesPort = new QName("http://services.soap/", "BenutzerservicesPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/DSE_Abgabe2Projekt/services/BenutzerservicesPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BenutzerservicesService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/DSE_Abgabe2Projekt/services/BenutzerservicesPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BenutzerservicesService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BenutzerservicesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BenutzerservicesService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public BenutzerservicesService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public BenutzerservicesService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public BenutzerservicesService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns BenutzerservicesSEI
     */
    @WebEndpoint(name = "BenutzerservicesPort")
    public BenutzerservicesSEI getBenutzerservicesPort() {
        return super.getPort(BenutzerservicesPort, BenutzerservicesSEI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BenutzerservicesSEI
     */
    @WebEndpoint(name = "BenutzerservicesPort")
    public BenutzerservicesSEI getBenutzerservicesPort(WebServiceFeature... features) {
        return super.getPort(BenutzerservicesPort, BenutzerservicesSEI.class, features);
    }

}
