<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="BenutzerservicesService" targetNamespace="http://services.soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://services.soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema">
  <import namespace="http://services.soap/" schemaLocation="benutzerservices_schema1.xsd"/>
</schema>
  </wsdl:types>
  <wsdl:message name="pruefeLogin">
    <wsdl:part name="parameters" element="tns:pruefeLogin">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="getBenutzerliste">
    <wsdl:part name="parameters" element="tns:getBenutzerliste">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="getBenutzerlisteResponse">
    <wsdl:part name="parameters" element="tns:getBenutzerlisteResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="pruefeLoginResponse">
    <wsdl:part name="parameters" element="tns:pruefeLoginResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="BenutzerservicesSEI">
    <wsdl:operation name="pruefeLogin">
      <wsdl:input name="pruefeLogin" message="tns:pruefeLogin">
    </wsdl:input>
      <wsdl:output name="pruefeLoginResponse" message="tns:pruefeLoginResponse">
    </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="getBenutzerliste">
      <wsdl:input name="getBenutzerliste" message="tns:getBenutzerliste">
    </wsdl:input>
      <wsdl:output name="getBenutzerlisteResponse" message="tns:getBenutzerlisteResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="BenutzerservicesServiceSoapBinding" type="tns:BenutzerservicesSEI">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="pruefeLogin">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="pruefeLogin">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="pruefeLoginResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="getBenutzerliste">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="getBenutzerliste">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="getBenutzerlisteResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="BenutzerservicesService">
    <wsdl:port name="BenutzerservicesPort" binding="tns:BenutzerservicesServiceSoapBinding">
      <soap:address location="http://localhost:8080/DSE_Abgabe2Projekt/services/BenutzerservicesPort"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
