package client.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2017-01-21T22:21:36.789+01:00
 * Generated source version: 3.1.8
 * 
 */
@WebServiceClient(name = "AlleServicesServiceClient", 
                  wsdlLocation = "http://localhost:9000/AlleServices?wsdl",
                  targetNamespace = "http://client.soap/") 
public class AlleServicesService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://services.soap/", "AlleServicesService");
    public final static QName AlleServicesPort = new QName("http://services.soap/", "AlleServicesPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:9000/AlleServices?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AlleServicesService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:9000/AlleServices?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AlleServicesService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AlleServicesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AlleServicesService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public AlleServicesService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public AlleServicesService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public AlleServicesService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns AlleServicesSEI
     */
    @WebEndpoint(name = "AlleServicesPort")
    public AlleServicesSEI getAlleServicesPort() {
        return super.getPort(AlleServicesPort, AlleServicesSEI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AlleServicesSEI
     */
    @WebEndpoint(name = "AlleServicesPort")
    public AlleServicesSEI getAlleServicesPort(WebServiceFeature... features) {
        return super.getPort(AlleServicesPort, AlleServicesSEI.class, features);
    }

}
