package client.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2017-01-21T22:21:36.778+01:00
 * Generated source version: 3.1.8
 * 
 */
@WebService(targetNamespace = "http://client.soap/", name = "AlleServicesSEIClient")
@XmlSeeAlso({ObjectFactory.class})
public interface AlleServicesSEI {

    @WebMethod
    @RequestWrapper(localName = "pruefeLogin", targetNamespace = "http://services.soap/", className = "soap.services.PruefeLogin")
    @ResponseWrapper(localName = "pruefeLoginResponse", targetNamespace = "http://services.soap/", className = "soap.services.PruefeLoginResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean pruefeLogin(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "benutzerAnlegen", targetNamespace = "http://services.soap/", className = "soap.services.BenutzerAnlegen")
    @ResponseWrapper(localName = "benutzerAnlegenResponse", targetNamespace = "http://services.soap/", className = "soap.services.BenutzerAnlegenResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean benutzerAnlegen(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.lang.String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        int arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        java.lang.String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        java.lang.String arg8
    );

    @WebMethod
    @RequestWrapper(localName = "benutzerloeschen", targetNamespace = "http://services.soap/", className = "soap.services.Benutzerloeschen")
    @ResponseWrapper(localName = "benutzerloeschenResponse", targetNamespace = "http://services.soap/", className = "soap.services.BenutzerloeschenResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean benutzerloeschen(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getProduktgruppeByName", targetNamespace = "http://services.soap/", className = "soap.services.GetProduktgruppeByName")
    @ResponseWrapper(localName = "getProduktgruppeByNameResponse", targetNamespace = "http://services.soap/", className = "soap.services.GetProduktgruppeByNameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public client.soap.Produktgruppe getProduktgruppeByName(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getPersonByUsername", targetNamespace = "http://services.soap/", className = "soap.services.GetPersonByUsername")
    @ResponseWrapper(localName = "getPersonByUsernameResponse", targetNamespace = "http://services.soap/", className = "soap.services.GetPersonByUsernameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public client.soap.Person getPersonByUsername(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "benutzerEinfAufheben", targetNamespace = "http://services.soap/", className = "soap.services.BenutzerEinfAufheben")
    @ResponseWrapper(localName = "benutzerEinfAufhebenResponse", targetNamespace = "http://services.soap/", className = "soap.services.BenutzerEinfAufhebenResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean benutzerEinfAufheben(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "benutzerEinfrieren", targetNamespace = "http://services.soap/", className = "soap.services.BenutzerEinfrieren")
    @ResponseWrapper(localName = "benutzerEinfrierenResponse", targetNamespace = "http://services.soap/", className = "soap.services.BenutzerEinfrierenResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean benutzerEinfrieren(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getProduktByID", targetNamespace = "http://services.soap/", className = "soap.services.GetProduktByID")
    @ResponseWrapper(localName = "getProduktByIDResponse", targetNamespace = "http://services.soap/", className = "soap.services.GetProduktByIDResponse")
    @WebResult(name = "return", targetNamespace = "")
    public client.soap.Produkt getProduktByID(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "adminAnlegen", targetNamespace = "http://services.soap/", className = "soap.services.AdminAnlegen")
    @ResponseWrapper(localName = "adminAnlegenResponse", targetNamespace = "http://services.soap/", className = "soap.services.AdminAnlegenResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean adminAnlegen(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.lang.String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        int arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        java.lang.String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        java.lang.String arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        double arg9
    );

    @WebMethod
    @RequestWrapper(localName = "gebotAbgeben", targetNamespace = "http://services.soap/", className = "soap.services.GebotAbgeben")
    @ResponseWrapper(localName = "gebotAbgebenResponse", targetNamespace = "http://services.soap/", className = "soap.services.GebotAbgebenResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean gebotAbgeben(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebMethod
    @RequestWrapper(localName = "getProduktgruppeList", targetNamespace = "http://services.soap/", className = "soap.services.GetProduktgruppeList")
    @ResponseWrapper(localName = "getProduktgruppeListResponse", targetNamespace = "http://services.soap/", className = "soap.services.GetProduktgruppeListResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<client.soap.Produktgruppe> getProduktgruppeList();

    @WebMethod
    @RequestWrapper(localName = "adressdatenAendern", targetNamespace = "http://services.soap/", className = "soap.services.AdressdatenAendern")
    @ResponseWrapper(localName = "adressdatenAendernResponse", targetNamespace = "http://services.soap/", className = "soap.services.AdressdatenAendernResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean adressdatenAendern(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        int arg4
    );

    @WebMethod
    @RequestWrapper(localName = "getProduktListe", targetNamespace = "http://services.soap/", className = "soap.services.GetProduktListe")
    @ResponseWrapper(localName = "getProduktListeResponse", targetNamespace = "http://services.soap/", className = "soap.services.GetProduktListeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<client.soap.Produkt> getProduktListe();

    @WebMethod
    @RequestWrapper(localName = "getVerkaufteProdukteVonBenutzer", targetNamespace = "http://services.soap/", className = "soap.services.GetVerkaufteProdukteVonBenutzer")
    @ResponseWrapper(localName = "getVerkaufteProdukteVonBenutzerResponse", targetNamespace = "http://services.soap/", className = "soap.services.GetVerkaufteProdukteVonBenutzerResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<client.soap.Produkt> getVerkaufteProdukteVonBenutzer(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "produktAendern", targetNamespace = "http://services.soap/", className = "soap.services.ProduktAendern")
    @ResponseWrapper(localName = "produktAendernResponse", targetNamespace = "http://services.soap/", className = "soap.services.ProduktAendernResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean produktAendern(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        double arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        int arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        java.lang.String arg6
    );

    @WebMethod
    @RequestWrapper(localName = "produktgruppeAnlegen", targetNamespace = "http://services.soap/", className = "soap.services.ProduktgruppeAnlegen")
    @ResponseWrapper(localName = "produktgruppeAnlegenResponse", targetNamespace = "http://services.soap/", className = "soap.services.ProduktgruppeAnlegenResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean produktgruppeAnlegen(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "produktgruppeLoeschen", targetNamespace = "http://services.soap/", className = "soap.services.ProduktgruppeLoeschen")
    @ResponseWrapper(localName = "produktgruppeLoeschenResponse", targetNamespace = "http://services.soap/", className = "soap.services.ProduktgruppeLoeschenResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean produktgruppeLoeschen(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "produktVerschieben", targetNamespace = "http://services.soap/", className = "soap.services.ProduktVerschieben")
    @ResponseWrapper(localName = "produktVerschiebenResponse", targetNamespace = "http://services.soap/", className = "soap.services.ProduktVerschiebenResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean produktVerschieben(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "sucheProdukt", targetNamespace = "http://services.soap/", className = "soap.services.SucheProdukt")
    @ResponseWrapper(localName = "sucheProduktResponse", targetNamespace = "http://services.soap/", className = "soap.services.SucheProduktResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<client.soap.Produkt> sucheProdukt(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "produktgruppeAendern", targetNamespace = "http://services.soap/", className = "soap.services.ProduktgruppeAendern")
    @ResponseWrapper(localName = "produktgruppeAendernResponse", targetNamespace = "http://services.soap/", className = "soap.services.ProduktgruppeAendernResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean produktgruppeAendern(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "getBenutzerliste", targetNamespace = "http://services.soap/", className = "soap.services.GetBenutzerliste")
    @ResponseWrapper(localName = "getBenutzerlisteResponse", targetNamespace = "http://services.soap/", className = "soap.services.GetBenutzerlisteResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<client.soap.Benutzer> getBenutzerliste();

    @WebMethod
    @RequestWrapper(localName = "gebotLoeschen", targetNamespace = "http://services.soap/", className = "soap.services.GebotLoeschen")
    @ResponseWrapper(localName = "gebotLoeschenResponse", targetNamespace = "http://services.soap/", className = "soap.services.GebotLoeschenResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean gebotLoeschen(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "passwortAendern", targetNamespace = "http://services.soap/", className = "soap.services.PasswortAendern")
    @ResponseWrapper(localName = "passwortAendernResponse", targetNamespace = "http://services.soap/", className = "soap.services.PasswortAendernResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean passwortAendern(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "getZumVerkaufStehendeProdukteVonBenutzer", targetNamespace = "http://services.soap/", className = "soap.services.GetZumVerkaufStehendeProdukteVonBenutzer")
    @ResponseWrapper(localName = "getZumVerkaufStehendeProdukteVonBenutzerResponse", targetNamespace = "http://services.soap/", className = "soap.services.GetZumVerkaufStehendeProdukteVonBenutzerResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<client.soap.Produkt> getZumVerkaufStehendeProdukteVonBenutzer(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "produktLoeschen", targetNamespace = "http://services.soap/", className = "soap.services.ProduktLoeschen")
    @ResponseWrapper(localName = "produktLoeschenResponse", targetNamespace = "http://services.soap/", className = "soap.services.ProduktLoeschenResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean produktLoeschen(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getGebotshistorieVonBenutzer", targetNamespace = "http://services.soap/", className = "soap.services.GetGebotshistorieVonBenutzer")
    @ResponseWrapper(localName = "getGebotshistorieVonBenutzerResponse", targetNamespace = "http://services.soap/", className = "soap.services.GetGebotshistorieVonBenutzerResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<client.soap.Produkt> getGebotshistorieVonBenutzer(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "produktAnlegen", targetNamespace = "http://services.soap/", className = "soap.services.ProduktAnlegen")
    @ResponseWrapper(localName = "produktAnlegenResponse", targetNamespace = "http://services.soap/", className = "soap.services.ProduktAnlegenResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean produktAnlegen(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        int arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.lang.String arg5
    );
}
